version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    expose:
      - "9000"
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - app:/var/www
    links:
      - webserver

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - app:/var/www:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
    ports:
      - "8000:80"
    networks:
      - app-network


volumes:
  app:
    driver: local
networks:
  app-network:
    driver: bridge