version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - "9000:80"
    networks:
      - app-network
    volumes:
      - app:/var/www/html/database
    environment:
      APP_NAME: "Petshop UEM"
      APP_DEBUG: "false"
      MAIL_MAILER: "smtp"
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
      MAIL_USERNAME: "mailhog"
      MAIL_PASSWORD: "mailhog"
      MAIL_ENCRYPTION: "null"
      MAIL_FROM_ADDRESS: "petshop@uem.br"
      MAIL_FROM_NAME: "Petshop UEM"

  mailhog:
    image: mailhog/mailhog
    networks:
      - app-network
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    restart: unless-stopped

volumes:
  app:
    driver: local
networks:
  app-network:
    driver: bridge